### ISSUE TITLE
info about instruction easy shell

### ISSUE THREAD

**Issue by hardlock75** [incidrthreat/iceriver_oc#1]
<img width="493" alt="image" src="https://github.com/incidrthreat/iceriver_oc/assets/58529389/77fb8aed-54fd-4bdd-a9d3-eff9ea877787">

you Forget a dot in search line

there is the correct line 
$6$6are2S2fRbvF580O$ZFI9YBCaL8K1WCyoW71EyNGjZyjjMd9gQFrkh/q3tvJWM/hOj4733n/5TdXJWYLaUbBOwb.iXOsmXxjmNmHb3/

i think he miss a dot on the replacement line, but dont know where.

<img width="493" alt="image" src="https://github.com/incidrthreat/iceriver_oc/assets/58529389/d21aadd1-08b9-4c34-995b-1c8a3e52b7a5">

**Comment by incidrthreat** [comment]
good catch, I'll verify the hashes.  Thanks!

**Comment by incidrthreat** [comment]
Ok, I have looked at it and the dot/period was an unintentional IDE mistake and has been updated.  Thanks for creating a ticket about this.

**Comment by authrequest** [comment]
You can also change bgchris168 password when you terminal in Eclipse using command: `passwd bgchris168`
This will change the password to whatever you want.

**Comment by incidrthreat** [comment]
> You can also change bgchris168 password when you terminal in Eclipse using command: `passwd bgchris168` This will change the password to whatever you want.

Excellent point, I'll add it to the guide!  Thank you!
