### ISSUE TITLE
19V 7.9A vs 19.5V 7.7A - which voltage to choose for 150W PSU?

### ISSUE THREAD

**Issue by defactoambassador** [incidrthreat/iceriver_oc#11]
They both have the same wattage of 150W, but there's 0.5V difference in voltage. Is it negligible?

I did notice that the Readme links to 19.5V adapters, while the 120W stock adapters use 19V.

**Comment by freideee** [comment]
0.5v should be fine to use, although i am unsure what's the long term effect to the board.
