### ISSUE TITLE
KS0 overclocked with update160.bgz, is 3.99% rejection acceptable

### ISSUE THREAD

**Issue by elmajdal** [incidrthreat/iceriver_oc#13]
After overclocking with update160.bgz, is the 3.99% pool rejection acceptable or this is considered too much ?

**Comment by incidrthreat** [comment]
This was a pretty common occurrence during our testing phase.  The testers that were solo mining on their own node saw a small percentage (0.1% - 2%) but mostly they showed 0% rejection.  The ones mining to pools saw an initial rejection like the one you show and then a drop off the longer they mined to the pool.  IIRC, majority of them dropped to 0% after a few days of uptime.

I understand that doesn't exactly provide you with an answer on if it is too much, but give it some time to run on the pool and let us know where it goes from here, be it up or down.

Join us on the Kaspa Discord if you have any further questions or want to interact with this amazing community. https://discord.com/invite/kS3SK5F36R

**Comment by elmajdal** [comment]
Hello @incidrthreat 

Thank you for the detailed feedback.

Will keep it running and report back after a week . 

Thanks

**Comment by incidrthreat** [comment]
I hope it helps and your rejection rate either decreases or falls to 0%.  Do not hesitate to reach out to us on discord as I'll be closing out this issue.  Thanks!
