### ISSUE TITLE
For KS1 new firmware issue

### ISSUE THREAD

**Issue by faradayads** [incidrthreat/iceriver_oc#14]
How do I restore my miner to a state without using ks1update25.bgz to use ks1OCupdate.bgz @incidrthreat

**Comment by incidrthreat** [comment]
With webgui access you'd use the Iceriver default software found here: `https://www.iceriver.io/firmware-download/`.  

If you do not have access to webgui, head over to `https://github.com/incidrthreat/iceriver_oc/blob/main/ECLIPSE.md` and follow the directions to gain Eclipse IDE access to your ASIC. Once connected, click on the `File System` tab at the bottom, then drag-n-drop the update.bgz firmware from the Iceriver site onto the `/var/volatile/tmp/bg/uploads` folder and restart.  Assuming you have not messed with any of the system files your ASIC will be returned to factory firmware.  Please let us know how this goes.

Join us on the Kaspa Discord if you have any further questions or want to interact with this amazing community. https://discord.com/invite/kS3SK5F36R
