### ISSUE TITLE
The 150 update file is the same as 160

### ISSUE THREAD

**Issue by NeroNuke** [incidrthreat/iceriver_oc#15]
I tried updating to the 150 oc file but it's getting me 160 hashrate. I also noticed that the filesize for these two is identical at 11.402 KB. Is this a mistake or am I doing something wrong? I factory reset my miner and then updated to the 150 file, but got 160 hashrate.

**Comment by incidrthreat** [comment]
The file size is the same bc the clocks we're adjusting bw the 150 and 160 files are nearly negligible.  So for example, in the 150 we set clock to 01 and in the 160 we set it to 03.
