### ISSUE TITLE
KS1 New firmware

### ISSUE THREAD

**Issue by faradayads** [incidrthreat/iceriver_oc#16]
What is the difference between ks1OCupdate.bgz and ks1update25.bgz? I used to use ks1OCupdate.bgz normally but now switching to ks1update25.bgz fails to overclock Even restoring factory Settings and cutting back to ks1OCupdate.bgz won't help. What file is ks1update25.bgz changed even if the factory Settings can not be changed? I can go back through the eclipse ide and reuse ks1OCupdate.bgz @incidrthreat

**Comment by incidrthreat** [comment]
The change was adding Iceriver's latest fw into the package to show stability for the hashrate in the webgui. The edits we made to OC is within the miner file Iceriver uses, which was not changed between `ks1OCupdate.bgz` and `ks1update25.bgz`.

When loading fw via Eclipse IDE make sure to load it into the `/var/volatile/tmp/bg/uploads/` folder and then restart.  This folder is the same as loading it through the webgui.

Join us on the Kaspa Discord if you have any further questions or want to interact with this amazing community. https://discord.com/invite/kS3SK5F36R

**Comment by tomekmak** [comment]
> The change was adding Iceriver's latest fw into the package to show stability for the hashrate in the webgui. The edits we made to OC is within the miner file Iceriver uses, which was not changed between `ks1OCupdate.bgz` and `ks1update25.bgz`.
> 
> When loading fw via Eclipse IDE make sure to load it into the `/var/volatile/tmp/bg/uploads/` folder and then restart. This folder is the same as loading it through the webgui.
> 
> Join us on the Kaspa Discord if you have any further questions or want to interact with this amazing community. https://discord.com/invite/kS3SK5F36R

This applies (target via eclipse) also for KS0 ?
