### ISSUE TITLE
update works fine but can't see hashrate 

### ISSUE THREAD

**Issue by iGill01** [incidrthreat/iceriver_oc#17]
no hashrate in gui but on mining pool getting 150ghz. in gui showing 0 . is that normal ?

**Comment by Topbcy** [comment]
after 8 hours ago
pool still get 150g hashrate now?
and webgui still showing 0?

**Comment by JustLook12** [comment]
Did you try restarting the miner and no normally you see hashrate in gui. I also had it once but restarted solved this.

**Comment by iGill01** [comment]
All good now thanks :)
