### ISSUE TITLE
KS0 compatible charger jack size

### ISSUE THREAD

**Issue by defactoambassador** [incidrthreat/iceriver_oc#18]
I decided to buy some new 150w laptop chargers to upgrade my KS0. 

The thing is, their connectors cannot be inserted into the machine because they are too big. Can anyone confirm if the jack needs to be 5.5mm output diameter?

**Comment by incidrthreat** [comment]
Which one did you purchase? They should all be 5.5*2.5mm and compatible.

**Comment by defactoambassador** [comment]
> Which one did you purchase? They should all be 5.5*2.5mm and compatible.

I bought MSI Gaming 150W from a local retailer (https://www.11st.co.kr/products/1048686576), which is the same as the third option. Though, I think this may be an issue with localization as the local retailer page mentions variable jacks. Please ignore the OP; can you confirm that 5.5x2.5mm is the compatible one? I'll just make sure the adapter I buy comes with 5.5x2.5mm then.
