### ISSUE TITLE
KS1 Instability Issue

### ISSUE THREAD

**Issue by C-SELLERS** [incidrthreat/iceriver_oc#19]
Using the 25% overclock on the KS1, one of my hashboards drops from 500GH/s to 380 GH/s 30 min avg over the course of a day.

The other board however is fine at ~590 GH/s. Curious if anyone else has this issue, or if there is a 10% overclock out there?

The same hashboard slightly underperforms on stock as well (450GH/s 30 min avg)

**Comment by vzubach** [comment]
After installing the update and rebooting, ASIC reaches a normal overall hashrate of approximately 1250 GH/s. 
But if the ASIC temperature rises up to 89-90 degrees, then the overall hashrate drops to approximately 570-600 GH/s (270-300 GH/s per board) and remains there until you reboot the ASIC again, even if the temperature returns to normal values.

**Comment by chad5150** [comment]
is that 89-90 degrees celsius or fahrenheit? If celsius that's ~195 degrees fahrenheit which is way to hot. You'll burn that machine right up. Its dropping hashrate for self preservation.

**Comment by velenet** [comment]
> After installing the update and rebooting, ASIC reaches a normal overall hashrate of approximately 1250 GH/s. But if the ASIC temperature rises up to 89-90 degrees, then the overall hashrate drops to approximately 570-600 GH/s (270-300 GH/s per board) and remains there until you reboot the ASIC again, even if the temperature returns to normal values.

in the page of mining setting Flag the fan opt and set at 50/60% . the problem it's out?? (refresh the page whitout fix the fan speed)
