### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by PaulSBit** [incidrthreat/iceriver_oc#2]
![image](https://github.com/incidrthreat/iceriver_oc/assets/9810573/29085645-ea40-429f-8d28-b39d2b34fb12)
You have mistake in address line. It need have a slash "/" after "R"
Right address is https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2023-09/R/eclipse-java-2023-09-R-win32-x86_64.zip&r=1

**Comment by incidrthreat** [comment]
You are absolutely correct, I forgot a `/` in the URL.  I'll fix it, thank you!
