### ISSUE TITLE
Plans for 110 or 130 overclocks

### ISSUE THREAD

**Issue by defactoambassador** [incidrthreat/iceriver_oc#25]
I was curious if there were plans for these two profiles, for people with rather bad silicon lotteries. The 150 OC does help immensely for people who couldn't do full 160 (thanks for that by the way).

**Comment by incidrthreat** [comment]
We haven't looked at making lower clocks for each mainly bc the bits being adjusted in the binary are negligible.  Some have the silicon lottery winnings to enjoy the 160GH and others unfortunately have to settle for the 120-140GH.  If we find time and it's an overwhelming community request, we'll consider it.
