### ISSUE TITLE
KS0 update last 150 Bios but ....

### ISSUE THREAD

**Issue by Giulio1974** [incidrthreat/iceriver_oc#27]
So , update was fine , but afeter 1 day , i see that every 3h miner stop mining on mypool and restart mining  after 1h , so my question was where go to mine ? there are some % of ming for developper ? 
tk

**Comment by Spindler360** [comment]
I can't confirm that. 100% go into the pool for me. Please check your internet connection if it is stable or try another pool like 2miners

**Comment by incidrthreat** [comment]
@Giulio1974
We have not added any dev % fee to anything.  100% of what you earn (aside from pool fees) go to the users/consumers.

There should not be anything causing the miner to restart.  Check that your fans are turned on.  In the latest Iceriver release (which is what our OC is based on) you have to enable fans.  Are you by chance overheating?

**Comment by chad5150** [comment]
I flashed the 150 and 160 oc and i also experience auto reboots. Temps are fine. they sit in a 69f room with exhaust for excess heat. I flashed down to 140 and that solved the issue. So 120 and 140 are the only ones that work on the machine. I have 3 others that flash just fine on all OC's, IDK but i gave up trying to figure it out.
