### ISSUE TITLE
update150.bgz fan to 100 autoset

### ISSUE THREAD

**Issue by Soumya001** [incidrthreat/iceriver_oc#28]
Please publish a version with fan at 100% by default as power issue continues the system will go to 50% fan by itself after restarting I want it to go 100% as can't be set by deafult

**Comment by Soumya001** [comment]
By deafult with this modified firmwire I see the fan going 50% by itself but can you publish a version where it goes to 100%

**Comment by Spindler360** [comment]
see https://github.com/incidrthreat/iceriver_oc/issues/8

**Comment by incidrthreat** [comment]
At this moment there is no edits available to the firmware that will force the fans to 100%.  By default in the iceriver fw they are off until a specific temp is reached and then they kick on.  You'll have to manually set the fans speed in the GUI and even that takes a couple saves to actually be set.  Iceriver did a terrible job compiling the webapp they use.
