### ISSUE TITLE
Ks3L wont go over 2th when oced

### ISSUE THREAD

**Issue by Tradition2** [incidrthreat/iceriver_oc#29]
i tried the firmware on one of  my KS3L and it wont go above 2TH 
i have 2 others and for those it works fine
any idea why?

Thank you

**Comment by mbunal** [comment]
can u tell me, what are 2 others powers and hashrates?

**Comment by Tradition2** [comment]
The other 2 are pulling 3150w+- and doing 6th

**Comment by incidrthreat** [comment]
> i tried the firmware on one of my KS3L and it wont go above 2TH i have 2 others and for those it works fine any idea why?
> 
> Thank you

It's silicon lottery really.  During our testing, only 1 of the 8 running the OC firmware couldn't hit the 6TH.  Would recommend flashing the iceriver firmware back onto the rig only pulling 2TH.
