### ISSUE TITLE
after accessing to ks3l via eclipse.

### ISSUE THREAD

**Issue by mbunal** [incidrthreat/iceriver_oc#30]
after accessing to ks3l via eclipse. hello, i followed your guide. is accessed to ks3l successfully. i added a new user with root privileges. then i flashed your ks3lupdate.bgz. unfortunately it did not work for me. then i flashed iceriver firmware again. it is working regularly. anyway, my root privileged account working still after 2 flashes. it is normal? if it is normal iceriver did not flash entire disk. just change some neccessary files... am i right?

**Comment by incidrthreat** [comment]
There is no need to access the KS3L via eclipse to update. Utilize the webgui to perform the update.

Changes you made to the system will persist through a reboot and reflash of any firmware.
