### ISSUE TITLE
KS0 not able to mine

### ISSUE THREAD

**Issue by vruzayev** [incidrthreat/iceriver_oc#32]
Hello. After my previous problem(was solved) I still have to reset my miners and upgrade them every 2-3 days. But it's ok, because I'm able to mine. now have other problem. Yesterday 2 my miners stopped mine. on WEB GUI shows Hashrate - 0, Diff - 0G, Shares - 0. Status connected. I'm not able to reset to Factory Settings by reset button on front of device. Hold few minutes with no result. Green LED still flashing, but Red one solid all time. I'm able to reset from GUI, but still not mine. Now GUI shows Factory firmware, but not mine.

**Comment by chad5150** [comment]
What pool you using? Ive had machines just stop mining but still showing connected a couple of times on K1 pool prior to any modifications. Ive went back to k1 on occassion and it still happens once in awhile.

**Comment by steve1ceo** [comment]
I just use Kaspa pool works great 0% rejection rate
Best to use just one pool on miner as it has been known to switch pools randomly

**Comment by JustLook12** [comment]
It sounds like it is not connected. Really connected you should see a difficulty. The status connected does not represent connected to be honest. Check your pool settings.

**Comment by vruzayev** [comment]
Thank you for responses. 
I use first original pool in factory firmware. Then tried 2Miners, Kriptex. 
All my ASICS work on local node. When I configure this defective ones to node, I see it in the bridge, but with hashrate 0. 

But I think major problem is when I try to perform hard reset to factory settings by button on face of ASIC, no reactions. I hold even 5 minutes but it not rebooted. But if I click on reset button on GUI screen, it rebooted and put original firmware. But still not working

**Comment by chad5150** [comment]
Is your machine connected to a router/switch downstream from the modem? What type of internet connection do you have? ie cable/dsl/fiber/satellite? what are your download speads? How old is your equipment? Try connecting the non hashing miner directly to the modem. Disconnect any routers/switches first from the modem.

**Comment by chad5150** [comment]
Are you pressing the recessed button for reset or the one that sticks out? factory reset is the recessed button.

**Comment by vruzayev** [comment]
> Is your machine connected to a router/switch downstream from the modem? What type of internet connection do you have? ie cable/dsl/fiber/satellite? what are your download speads? How old is your equipment? Try connecting the non hashing miner directly to the modem. Disconnect any routers/switches first from the modem.

Connected to router together with other 3 ASICs. 3 work good, but 2 of them not working. On one of Russian forums got information about corrupted NAND FLASH firmware. Just received T48 programmer. Tomorrow will try to make a copy of firmware from one of the working ASICs and re-flash defective ones. Will keep you posted about results

**Comment by vruzayev** [comment]
Re-flashed NAND Flash from one of worked ASIC to defective two. Both of them start to mine. Only thing need to change MAC address in bin file. It is located on address 00420210-20
Cost 60 CAD for T48 programmer from Aliexpress and 20 CAD for adaptor. Cheaper than send to China for repair.

You can close problem. Solved

**Comment by barbiudo** [comment]
@vruzayev is it easy to reflash nand flash? I have ks0 pro and it does not mine..

**Comment by brianvz1980** [comment]
@vruzayev noticed you having a similar challenge as what I am having, would you be able to advise on how you managed to resolved it please? Would appreciate it !
