### ISSUE TITLE
KS0 OC update after factory reset displays an error message, "Request Timeout."

### ISSUE THREAD

**Issue by ethvilet** [incidrthreat/iceriver_oc#34]
Hey All,

I am hoping that someone can help me with my issue. I have had some great help to use eclipse to upload the OC update through the file system. However, after a hard restart the OC update will not take and the file disappears.  I did have an OC update that would work but I wanted to test something out and did a factory reset. 

The OC update through eclipse is added to the file system explorer at  VAR -> volatile -> tmp -> bg -> uploads. Any ideas?

**Comment by ethvilet** [comment]
I wonder if it has to do with the API access settings (Privileged vs. Restricted) as this has happened to other ASIC miners: https://support.awesomeminer.com/support/solutions/articles/35000197421-privileged-api-access#Restricted%20and%20Privileged%20Mode 

This would make sense given my history of failed updates due to a "request timeout."

**Comment by JustLook12** [comment]
Hi there after a hard reset, the firmware goes back to original firmware, so you need to upgrade your machine with the one from Iceriver first. After that i you can either upload through eclips or use the other update files to upgrade.

**Comment by ethvilet** [comment]
Fixed. I used the miner.bgz file using the eclipse method and trying a different folder.
