### ISSUE TITLE
ks1

### ISSUE THREAD

**Issue by faradayads** [incidrthreat/iceriver_oc#35]
When will this ks1 be available? "We are working on a 40% bump as well, so stay tuned for that." @incidrthreat

**Comment by incidrthreat** [comment]
> When will this ks1 be available? "We are working on a 40% bump as well, so stay tuned for that." @incidrthreat

We're hoping to have it available soon.  My OC partner has been the one leading the 40% OC for the KS1 and KS2.  He's run into some issues at home with a flooded basement and is dealing with that currently. The testing phase has been going for a few weeks now and has had decent results.  The caveat for the 40% OC is that it pushes the PSUs close to their max output, so it's use will be at a very very VERY cautious warning level.  Hope that helps and we apologize for the delay.
