### ISSUE TITLE
Ks0 question - Request  : Will downclocking increase the efficiency of machine Ks0 and if so will there be releases with downclocks ? 

### ISSUE THREAD

**Issue by JustLook12** [incidrthreat/iceriver_oc#36]
Hi there, 

Looking at long run, staying profitable the watt/gh is key, my question we know that oc increases hash but also efficiency decreases. Will downclock increase efficiency and if yes is it possible to have some Mod files with lower clocks (for those who want to be more efficient instead of fast. 

Kind regards

**Comment by chad5150** [comment]
An easy fix for your question is to go back to stock if you want more efficiency back. These machines are highly efficient as they are so going back even more seems silly to me. My opinion is if you're still profitable after accounting for electricity the more hashrate the better.  Do the math and you will find what is comfortable for you. There are tons of sites out there that can help with calculations.
