### ISSUE TITLE
KS2

### ISSUE THREAD

**Issue by Gooseman786** [incidrthreat/iceriver_oc#37]
Hi

My KS2 mines at around 2056ghz. when I tried the OC it drops to 1350GHZ. When i restored to factory settings and then upgraded from Iceriver I get back to the 2056GHZ.
Any ideas as to what I could be doing wrong?
I also downloaded the update and used the upgrade option on the asic.

Regards

**Comment by faradayads** [comment]
use 40% may can work, i guess
