### ISSUE TITLE
KS0 OC150/160 ERROR

### ISSUE THREAD

**Issue by Phitrok** [incidrthreat/iceriver_oc#38]
Hello,

when I upgrade the ks0 to 150 or 160gh it fails to communicate with the pool and stays at 0gh and 0 accepted requests even when connected to the pool.

I am currently mining at 140gh maintained with oc file 140.

Does anyone have the same problem?

I need the miner.bgz file to test the eclipse method if someone is kind enough to re-upload it I would appreciate it.

**Comment by incidrthreat** [comment]
That means that you are overwhelming your miner clock speeds and it wont mine.  The 140GH for your KS0 is the correct one.
