### ISSUE TITLE
Fan settings not holding

### ISSUE THREAD

**Issue by chad5150** [incidrthreat/iceriver_oc#4]
Fan settings do not hold. I have 2 units that i set to 100%, save it and goes back to 0% I have one that holds the fan settings.

**Comment by incidrthreat** [comment]
> Fan settings do not hold. I have 2 units that i set to 100%, save it and goes back to 0% I have one that holds the fan settings.

For which model?  If you are referring to the KS0 models, there is a known glitch in the webgui (across all models) that causes the fan speeds to not show status properly and do not auto-start upon reboots.  The webgui is by far the worst built frontend with numerous issues.  Iceriver will likely not fix it and the changes will be left for the community to fix.  Sometimes it takes a few sets and saves to get it working properly

**Comment by chad5150** [comment]
Yes ks0. I should have been more specific. The fan settings always held. After using the modified firmware, 2 I modified the fan settings held and the 3 others did not. I know this as the temps skyrocket and I can see the fans not spinning on the physical machine.  Agreed on the buggy interface.

Thank You,
Chad Hansen
________________________________
