### ISSUE TITLE
KS2 40% OC 

### ISSUE THREAD

**Issue by KaspaBeast** [incidrthreat/iceriver_oc#43]
So I tried the new 40% OC but it's not reaching the hashrate it was supposed to which is 2800 am reaching like 2600 and a high increase in watts. 

Does anyone know what's the issue or should I just go back to 25% OC?

**Comment by steve1ceo** [comment]
Personally I would stay with the 20% to much overclocking could damage the machine, then there is the silicon lottery

**Comment by ironwolfm** [comment]
is there change on your power cunsumption more than 25%?

**Comment by spacedive** [comment]
Mine kept rebooting at 40%. The 25% works great but you lose the ability to monitor the ASIC board temperature in the miner dashboard. It's the only thing keeping me from donating, at the moment.

**Comment by incidrthreat** [comment]
@spacedive Check out PBFarmer's OC, we cannot recommend it enough.  He's done some amazing work.  It has more user control and provides better output in the webgui, including chip temps.  We fully support PBFarmer's OC efforts. No donation needed as PBFs firmware has a 1% dev fee built in that goes directly to THE Kaspa Dev fund. https://github.com/rdugan/iceriver-oc

We have slowed down efforts on this repo to focus more on PBFarmer's OC and the KS0 Pro OC.  We will still release set % OCs and will likely revamp our firmware releases in the next coming months.  We hope this helps.  Please do not hesitate to stop by and chat with us on the Kaspa discord: https://discord.com/invite/kS3SK5F36R
