### ISSUE TITLE
overclocking the new KS0 PRO?

### ISSUE THREAD

**Issue by jkdi** [incidrthreat/iceriver_oc#45]
hi,
is there a possibility of overclocking the new KS0 PRO? it has a factory hash-rate from around 200gh/s 

thx!

**Comment by incidrthreat** [comment]
There is a release from TShitty for 1300 KAS but it also requires an investment of a 230-300w PSU.  We are working on a KS0 Pro free OC.  Please have patience.

**Comment by qidao2** [comment]
How is the project progressing

**Comment by dmsteknoloji** [comment]
Ks0 Pro için OC bekliyorum. bahışlar için hazırım.

**Comment by IwasthefirstNerrdAlerrt** [comment]
How’s this going?  Just got my ks0 pro and would love to apply the oc for it!

**Comment by thedonknowsncswic** [comment]
> There is a release from TShitty for 1300 KAS but it also requires an investment of a 230-300w PSU. We are working on a KS0 Pro free OC. Please have patience.

I'd be ok paying for it, but 130$ is a scam.  an 800$ machine now a 930$ machine is never going to ROI at this rate.   If I hacked this thing, I'd sell the software for $25.  You dont need to scam the hell out of it.  Man that guy is garbage.

**Comment by incidrthreat** [comment]
@thedonknowsncswic @IwasthefirstNerrdAlerrt @dmsteknoloji @qidao2 

KS0 Pro OC has been released by our very own PBFarmer.  It can be found here: `https://github.com/rdugan/iceriver-oc`.  I will be updating this github with recommended PSUs, Cooling, and some community tips & treats to help keep your KS0Pro's cool.

We do not recommend purchasing TSwifts OC as it alters host files and has caused numerous members to burn up their ASICs.
