### ISSUE TITLE
Last 25KS2update have no temps

### ISSUE THREAD

**Issue by neoptt** [incidrthreat/iceriver_oc#46]
Hi, I have no temps showing on my KS2 after I update to the 25% OC file, any solution??

Thanks
![Captura de ecrã 2023-11-29 203026](https://github.com/incidrthreat/iceriver_oc/assets/131161066/9d4131c9-146d-45dd-813b-f41ca42cfe5f)

**Comment by incidrthreat** [comment]
The temps shouldnt disappear, try restarting the miner.  The webgui is not the best built so sometimes you will see duplicate information if refreshing too fast or information not showing up.
