### ISSUE TITLE
cooling solution for ks0pro

### ISSUE THREAD

**Issue by Cyl0nius** [incidrthreat/iceriver_oc#47]
remove the plates on both sides and install the adapter for standard 120mm fan on the power connector side.
it blows out the hot air.

feel free to donate me a beer.

![github](https://github.com/incidrthreat/iceriver_oc/assets/119928546/1350f4b0-b2ee-4200-a6a7-1e6a06f5fb4d)

since github does not support stl file format, it is provided as zip file.

[ks0_fan_adapter.zip](https://github.com/incidrthreat/iceriver_oc/files/13692308/ks0_fan_adapter.zip)

**Comment by vasiliySha** [comment]
Do you have a photo in real life?
