### ISSUE TITLE
KS0 Red & Green Lights continuously flashing

### ISSUE THREAD

**Issue by alistairjd01** [incidrthreat/iceriver_oc#49]
Good Day,

I hope you are well.

My KS0 has been mining fine up until today when it suddenly just stopped mining upon further investigation I see both indicator lights are just continuously flashing, I have tried to reset the board using the reset but have had no luck, is there any other way of flashing the board to default firmware to see if the board is still working or is this error an indication the board is fried?

Thank you in advance

Regards
Alistair Davies

**Comment by chad5150** [comment]
[ECLIPSE.md](https://github.com/incidrthreat/iceriver_oc/files/13766437/ECLIPSE.md)
not quite the same situation but to get back to a full factory i once had to use eclipse to get into the file system. There is a tutorial on the page with all the folder/files/readme's. There is a readme towards the bottom that explains to setup eclipse. Disregard the rest. Delete everything in green and go pull the power cord out from the machine, wait about 10 seconds, and plug it back in. This will create all the necessary factory default files. Should be good to go after that. Remember any OC is at your own risk. I added the eclipse tutorial also.
![Screenshot 2023-12-25 080926](https://github.com/incidrthreat/iceriver_oc/assets/102040661/0b4e06e2-163a-4f02-b245-1ffdce9b50ac)
[ECLIPSE.md](https://github.com/incidrthreat/iceriver_oc/files/13766437/ECLIPSE.md)

**Comment by mbunal** [comment]
can I use this for ks3l too?

**Comment by chad5150** [comment]
did this work for you on the ks0 and yes you can use the same method for any of the machines?

**Comment by alistairjd01** [comment]
Hi support,

No it never worked because it wasn't the issue in the end. The was resolved
by changing out a faulty psu

Thank you for the reply and the time taken to respond

Kind Regards
Alistair Davies
