### ISSUE TITLE
KS2 update fails.

### ISSUE THREAD

**Issue by jet55555** [incidrthreat/iceriver_oc#5]
I failed to update the KS2 OC firmware, web GUI notice: miner returns failed. And the hashrate has no chage. 
![image](https://github.com/incidrthreat/iceriver_oc/assets/35908528/360f439f-b7cf-4b87-aa0d-7aa9bebeadb3)

**Comment by authrequest** [comment]
Try doing it with SSH, utilize the jm executable that decrypts the update and then place the miner.bgz in /var/update this will work

**Comment by incidrthreat** [comment]
@jet55555 Did you download the file from: `https://github.com/incidrthreat/iceriver_oc/raw/main/KS2/files/ks2OCupdate.bgz` or did you just right-click and save as?  Sometimes there are github artifacts that get pulled in if you download using right-click method.  Check the hash of the one you downloaded to the one we have listed in the README.

**Comment by jet55555** [comment]
How exactly do it with ssh?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月3日(星期二) 凌晨1:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [incidrthreat/iceriver_oc] KS2 update fails. (Issue #5)





 
Try doing it with SSH, utilize the jm executable that decrypts the update and then place the miner.bgz in /var/update this will work
