### ISSUE TITLE
how to extract .BGZ file?

### ISSUE THREAD

**Issue by Dyrindyi** [incidrthreat/iceriver_oc#50]
I want to extract the firmware file to have a look into the code. I have tried diffrent method like Gunzip etc to open it up, but no success. Please suggest me how to extract .bgz firmware file. Thanks in Advance!

**Comment by incidrthreat** [comment]
To extract the firmware from the BGZ file you need to use the custom developed extraction method that's on the miner itself called `jm`.  No passwords are set on the firmware file just a basic AES256 encryption that's easy to get around.  Mind you, you will need an ARM env to do this as the binary is written for ARM architecture.  You can do it directly on the ASICs themselves or extract and run elsewhere.  The commands for extraction are 

`./jm  *miner*.bgz  miner.tar`
`tar -zxmf miner.tar`

**Comment by thedonknowsncswic** [comment]
very cool, thank you!!!!
