### ISSUE TITLE
25KS2update.bgz firmware shows blank "Hash board" section 

### ISSUE THREAD

**Issue by spacedive** [incidrthreat/iceriver_oc#51]
Hash board temperatures are not displayed after installing the 25KS2update.bgz firmware.

![image](https://github.com/incidrthreat/iceriver_oc/assets/887818/729120f2-c53f-4732-8d99-e304573fc2ec)

**Comment by spacedive** [comment]
Any update on this?

**Comment by incidrthreat** [comment]
Check out PBFarmer's OC, we cannot recommend it enough.  He's done some amazing work.  It has more user control and provides better output in the webgui, including chip temps.  We fully support PBFarmer's OC efforts. https://github.com/rdugan/iceriver-oc

We have slowed down on this community effort on this repo to focus more on PBFarmer's OC.  We will still release set % OCs and will likely revamp our firmware releases in the next coming months.  We hope this helps.  Please do not hesitate to stop by and chat with us on the Kaspa discord: https://discord.com/invite/kS3SK5F36R
