### ISSUE TITLE
I can't access my iceriver via eclipse

### ISSUE THREAD

**Issue by winubleteg** [incidrthreat/iceriver_oc#53]
I have followed the steps in the guide to enter via eclipse but none of my iceriver's IP appears in the program. I have tried to add them manually and it does not appear either.

**Comment by thedonknowsncswic** [comment]
I cant access mine from ssh.  I think the directions were written for KS0 100GH models (not the pro models).  I suspect something is different between the 2 versions.   I will try to scan for open ports and see if anything besides port 80 is open

**Comment by alistairjd01** [comment]
Hi Support,

this ticket can be closed i have managed to reset the miner to default using the reset button, thank you for your time

**Comment by JWTMining** [comment]
I have an Iceriver KS5L but its IP will not appear in the new connection browser.  Is something different with the new firmware for the KS5L?
