### ISSUE TITLE
Auto fan mode on KS0 and KS1

### ISSUE THREAD

**Issue by Aluminer14** [incidrthreat/iceriver_oc#8]
I don’t see if it’s possible or not to have an auto fan option like in the previous update form iceriver with this overclocks firmwares. Can you enlighten me please?

**Comment by Spindler360** [comment]
it is. same as bevore
![image](https://github.com/incidrthreat/iceriver_oc/assets/36817738/4c5050c3-3c93-41f2-a64c-bb3c47c1d02e)

**Comment by Aluminer14** [comment]
But I need to click on the check mark an set to 0%?

Spindler360 ***@***.***> escreveu em qua., 4/10/2023 às 16:47
:

**Comment by Spindler360** [comment]
I think so. I don't remember exactly. If the marker disappears after that, the default mode is active. Try it out for yourself ([read more](https://github.com/incidrthreat/iceriver_oc/issues/4#issuecomment-1743623655)). But also look at the temps and your fan speed on the home dashboard.

**Comment by JustLook12** [comment]
i believe : 
- if you thick the checkbox and set a % you manually override everything.
-  But if you do not thick the checkbox, but just press save it will go on "auto" mode.

**Comment by incidrthreat** [comment]
At this moment there is no edits available to the firmware that will force the fans to 100%. By default in the iceriver fw they are off until a specific temp is reached and then they kick on. You'll have to manually set the fans speed in the GUI and even that takes a couple saves to actually be set. Iceriver did a terrible job compiling the webapp they use.
