### ISSUE TITLE
KS1 upgrade problem

### ISSUE THREAD

**Issue by andy1207** [incidrthreat/iceriver_oc#9]
I tried to upgrade my KS1 mining machine, but encountered the following issues:
1. Iceberg Official Website: After upgrading, when the KS1 connects to the server, it waits for about 10 minutes, but there is no hashing power at all, and the power consumption remains around 50W.
Version   BOOT_2_0.BIN image_1.0 1597994_ks1miner 1597994_ks1bg

2. Similarly, updating the firmware form here, the KS1 connects to the serve, and waits for about 10 minutes, but there is no hashing power at all, and the power consumption remains around 50W.

3. Restore factory settings: After the KS1 connects to the server, it has hashing power in about 2 minutes, approximately 1T, and power consumption is around 600W.
 Version   BOOT_2_0.BIN image_1.0 sy0620_ks2miner 0616_ks2bg 

It's strange that my KS1's factory firmware is displayed as "Version BOOT_2_0.BIN image_1.0 sy0620_ks2miner 0616_ks2bg."
Does anyone know how to resolve this issue?
![Snap4](https://github.com/incidrthreat/iceriver_oc/assets/66779431/30e7a77b-379b-4307-b4cc-af259f8f85ca)

**Comment by incidrthreat** [comment]
The KS1s take a bit to kick up and hash, so patients is ideal in this situation.  Looking at the image above, you've accepted 2 shares which means you're hashing.  Reach out to us or anyone on the Kaspa discord, everyone is helpful.

https://discord.com/invite/kS3SK5F36R
